VENDOR=samsung
DEVICE=sc06d
OUTDIR=vendor/$VENDOR/$DEVICE
MAKEFILE=../../../$OUTDIR/$DEVICE-vendor-blobs.mk

(cat << EOF) > $MAKEFILE
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \\
	$OUTDIR/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \\
	$OUTDIR/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \\
	$OUTDIR/proprietary/lib/libv8.so:obj/lib/libv8.so

PRODUCT_COPY_FILES += \\
EOF

LINEEND=" \\"
COUNT=`wc -l device-proprietary-files.txt | awk {'print $1'}`
DISM=`egrep -c '(^#|^$)' device-proprietary-files.txt`
COUNT=`expr $COUNT - $DISM`
for FILE in `egrep -v '(^#|^$)' device-proprietary-files.txt`; do
  COUNT=`expr $COUNT - 1`
  if [ $COUNT = "0" ]; then
    LINEEND=""
  fi
  echo "	$OUTDIR/proprietary/$FILE:system/$FILE$LINEEND" >> $MAKEFILE
done

(cat << EOF) >> $MAKEFILE

PRODUCT_COPY_FILES += \\
EOF

LINEEND=" \\"
COUNT=`wc -l ../d2-common/common-proprietary-files.txt | awk {'print $1'}`
DISM=`egrep -c '(^#|^$)' ../d2-common/common-proprietary-files.txt`
COUNT=`expr $COUNT - $DISM`
for FILE in `egrep -v '(^#|^$)' ../d2-common/common-proprietary-files.txt`; do
  COUNT=`expr $COUNT - 1`
  if [ $COUNT = "0" ]; then
    LINEEND=""
  fi
  echo "        $OUTDIR/proprietary/$FILE:system/$FILE$LINEEND" >> $MAKEFILE
done


##### apps

(cat << EOF) >> $MAKEFILE

PRODUCT_PACKAGES += \\
EOF

LINEEND=" \\"
COUNT=`wc -l device-proprietary-apps.txt | awk {'print $1'}`
DISM=`egrep -c '(^#|^$)' device-proprietary-apps.txt`
COUNT=`expr $COUNT - $DISM`
for FILE in `egrep -v '(^#|^$)' device-proprietary-apps.txt`; do
  APPDIR=`echo $FILE | sed -e "s/\.[^.]*$//g"`
  COUNT=`expr $COUNT - 1`
  if [ $COUNT = "0" ]; then
    LINEEND=""
  fi
  echo "	$APPDIR$LINEEND" >> $MAKEFILE
done


(cat << EOF) > ../../../$OUTDIR/$DEVICE-vendor.mk
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files

\$(call inherit-product, vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk)
EOF

(cat << EOF) > ../../../$OUTDIR/BoardConfigVendor.mk
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
EOF


##### apps
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/MobileFeliCaWebPlugin/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := MobileFeliCaWebPlugin
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := MobileFeliCaWebPlugin
LOCAL_SRC_FILES := MobileFeliCaWebPlugin.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/MobileFeliCaMenuApp/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := MobileFeliCaMenuApp
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := MobileFeliCaMenuApp
LOCAL_SRC_FILES := MobileFeliCaMenuApp.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/FdtpApplication/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := FdtpApplication
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := FdtpApplication
LOCAL_SRC_FILES := FdtpApplication.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/AppWidgetPicker/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := AppWidgetPicker
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := AppWidgetPicker
LOCAL_SRC_FILES := AppWidgetPicker.apk
  
include \$(BUILD_PREBUILT)
endif
EOF


#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/TriangleAway/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := TriangleAway
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := TriangleAway
LOCAL_SRC_FILES := TriangleAway.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/MobileTV_JPN/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := MobileTV_JPN
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := MobileTV_JPN
LOCAL_SRC_FILES := MobileTV_JPN.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/FeliCaLock/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := FeliCaLock
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := FeliCaLock
LOCAL_SRC_FILES := FeliCaLock.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/MobileFeliCaClient/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := MobileFeliCaClient
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := MobileFeliCaClient
LOCAL_SRC_FILES := MobileFeliCaClient.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/MobileFeliCaWebPluginBoot/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := MobileFeliCaWebPluginBoot
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := MobileFeliCaWebPluginBoot
LOCAL_SRC_FILES := MobileFeliCaWebPluginBoot.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/FeliCaTest/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := FeliCaTest
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := FeliCaTest
LOCAL_SRC_FILES := FeliCaTest.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/MobileFeliCaSettingApp/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := MobileFeliCaSettingApp
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := MobileFeliCaSettingApp
LOCAL_SRC_FILES := MobileFeliCaSettingApp.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/FdtpMfcAccess/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := FdtpMfcAccess
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := FdtpMfcAccess
LOCAL_SRC_FILES := FdtpMfcAccess.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/FeliCaRemoteLock/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := FeliCaRemoteLock
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := FeliCaRemoteLock
LOCAL_SRC_FILES := FeliCaRemoteLock.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

#####
(cat << EOF)  > ../../../vendor/$VENDOR/$DEVICE/proprietary/MobileFeliCaMenuMainApp/Android.mk

ifeq (\$(TARGET_DEVICE),sc06d)
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := MobileFeliCaMenuMainApp
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := MobileFeliCaMenuMainApp
LOCAL_SRC_FILES := MobileFeliCaMenuMainApp.apk
  
include \$(BUILD_PREBUILT)
endif
EOF

